version: "3"

services:
  openhands:
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    image: openhands:latest
    container_name: openhands-app-${DATE:-dev}
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SANDBOX_RUNTIME_CONTAINER_IMAGE:-docker.all-hands.dev/all-hands-ai/runtime:0.32-nikolaik}
      #- SANDBOX_USER_ID=${SANDBOX_USER_ID:-1234} # enable this only if you want a specific non-root sandbox user but you will have to manually adjust permissions of openhands-state for this user
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-$PWD/workspace}
      - OPENHANDS_RUNNING_IN_DOCKER=true # Add env var to signal docker context if needed
      - LOG_LEVEL=${LOG_LEVEL:-WARNING} # Set log level for development
      - POETRY_VIRTUALENVS_CREATE=false # Optional: Prevent poetry from creating venvs inside container if source is mounted
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/opt/workspace_base
    depends_on:
      - neovim-runtime-builder
    networks:
      - openhands-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  neovim-runtime-builder:
    build:
      context: ./neovim-runtime
      dockerfile: Dockerfile
    image: neovim-runtime
    command: "echo 'Neovim runtime image built successfully'"
    networks:
      - openhands-network

networks:
  openhands-network:
    driver: bridge
